version: '3.8'

services:
  form:
    build: .
    restart: unless-stopped
    # Allow overriding the backend API URL via an environment variable when running
    # the Form compose standalone. By default (when included in the top-level
    # compose) it will use the service name `backend` on the compose network.
    environment:
      API_URL: "${API_URL:-http://backend:8000}"
    ports:
      - '5000:5000'
